const transformers = [
  "None",
  "StringToBool",
  "EpochToTimestamp",
  "FormatMac",
  "FormatTCPProtocol",
  "EpochSecondsToTimestamp",
  "TimestampToMilliseconds",
  "ToInteger",
  "ToString",
  "ToLowercaseArray",
  "ToBase64",
  "ToFilePath",
  "ToDirectoryPath",
  "ToFileName",
  "ToDomainName",
  "ToIPv4",
  "DateTimeToUnixTimestamp",
  "NaiveToUTC",
  "TimestampToUTC",
  "SetToOne",
  "FilterIPv4List",
  "FilterIPv6List",
  "ValueToList",
  "GraphIDToPID",
];

export default transformers;
