coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
    patch: off
ignore:
  - "stix_shifter/scripts/"  # ignore folders and all its contents
  - "conftest.py"
  - "generate_requirements.py"
  - "main.py"
  - "setup.py"
comment:
  require_changes: true