version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    ports:
      - 9900:9200
  splunk:
    image: splunk/splunk:latest
    hostname: splunk
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes --seed-passwd changeme
      SPLUNK_ENABLE_LISTEN: 9997
      SPLUNK_ADD: tcp 1514
      SPLUNK_USER: root
      SPLUNK_CMD: "edit user admin -password translator_test -role admin -auth admin:changeme"
    ports:
      - "8900:8000"
      - "8989:8089"
