# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: stix-shifter

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: '**/requirements-dev.txt'
    - name: Install dependencies
      run: |
        python generate_requirements.py
        pip install --upgrade pip setuptools wheel
        pip install -r requirements-dev.txt
    - name: Lint with flake8
      run: |
        pip install --upgrade flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
        # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run test and generate coverage report
      run: |
        pip install pytest-cov
        pip install codecov
        pytest --cov=./ --cov-report=xml
    - name: Upload coverage information to Codecov
      uses: codecov/codecov-action@v3
      with:
        version: "v0.2.6"
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)